site_name: Empire Documentation
theme: readthedocs
pages:
  - 'Introduction': 'index.md'
  - Overview:
    - "Known Limitations": "known_limitations.md"
  - Getting Started:
    - "Quickstart: Installing": "quickstart_installing.md"
    - "Quickstart: Using": "quickstart_using.md"
    - "Configuration": "configuration.md"
    - "Production Best Practices": "production_best_practices.md"
  - Users Guide:
    - "Deploying an Application": "deploying_an_application.md"
    - "Exposing an app publicly": "exposing_an_app_publicly.md"
    - "SSL Certs": "ssl_certs.md"
    - "CloudFormation Resources": "cloudformation_resources.md"
  - Hacking on Empire:
    - "Contribution Guidelines & Bug Reporting": "contributing.md"
  - Reference:
    - "Troubleshooting": "troubleshooting.md"


