version: 2

defaults: &defaults
  working_directory: /go/src/github.com/remind101/empire

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test
      - vet
      - docker_image
      - cloudformation_template:
          filters:
            branches:
              only: master
      - release

jobs:
  build:
    <<: *defaults

    docker:
      - image: circleci/golang:1.7

    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: sudo apt-get update -qq && sudo apt-get install -yy libxml2-dev libxmlsec1-dev liblzma-dev pkg-config xmlsec1
      - run: make cmds
  test:
    <<: *defaults

    docker:
      - image: circleci/golang:1.7
        environment:
          SHELL: /bin/bash
      - image: circleci/postgres:9.3
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: empire

    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: sudo apt-get update -qq && sudo apt-get install -yy libxml2-dev libxmlsec1-dev liblzma-dev pkg-config xmlsec1
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: make test
  vet:
    <<: *defaults

    docker:
      - image: circleci/golang:1.7

    steps:
      - checkout
      - run: make vet

  docker_image:
    docker:
      - image: remind101/docker-build
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker-build

  release:
    <<: *defaults

    docker:
      - image: circleci/golang:1.7

    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: sudo apt-get update -qq && sudo apt-get install -yy libxml2-dev libxmlsec1-dev liblzma-dev pkg-config xmlsec1
      - run: make release

  cloudformation_template:
    docker:
      - image: circleci/python:2.7
        environment:
          AWS_REGION: us-east-1

    steps:
      - checkout
      - run:
          name: Install AWS cli
          command: sudo pip install awscli
      - run: aws s3 cp docs/cloudformation.json s3://empirepaas/cloudformation.json --acl public-read
